services:
  laravel:
    container_name: jobhound_backend
    restart: always
    build:
      context: ./server/rest
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: jobhound
      DB_USERNAME: jobhound
      DB_PASSWORD: secret
    depends_on:
      - db
    networks:
      - app-network

  nextjs:
    container_name: jobhound_frontend
    restart: always
    build:
      context: ./client/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/web:/app
    depends_on:
      - laravel
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: jobhound # Ensure this matches laravel service
      MYSQL_USER: jobhound
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
