name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Install Node.js and npm if not installed
            if ! command -v npm &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
              sudo apt install -y nodejs
            fi

            # Ensure pnpm is installed on the server
            if ! command -v pnpm &> /dev/null; then
              npm install -g pnpm
            fi

            # Navigate to the project directory
            cd /var/www/JobHound/

            # Pull the latest code from the main branch
            git pull origin main

            # Check the status of the repository
            git status

            # Install production dependencies for the client
            cd client/web
            pnpm install --prod

            # Go back to the project root
            cd ../..

            # Install PHP dependencies for the server
            cd server/rest
            composer install --no-dev --prefer-dist

            # Restart services
            sudo systemctl restart frontend 
            sudo systemctl restart backend
